services:
  hmpps-electronic-monitoring-compliance-api:
    image: ghcr.io/ministryofjustice/hmpps-electronic-monitoring-compliance-api:latest
    networks:
      - hmpps
    container_name: hmpps-electronic-monitoring-compliance-api
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/8080"]
    environment:
      - SERVER_PORT=8080
      - HMPPS_AUTH_URL=http://hmpps-auth:8080/auth
      - SPRING_PROFILES_ACTIVE=dev

  hmpps-auth:
    image: ghcr.io/ministryofjustice/hmpps-auth:latest
    networks:
      - hmpps
    container_name: hmpps-auth
    ports:
      - "8090:8080"
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/8080"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - APPLICATION_AUTHENTICATION_UI_ALLOWLIST=0.0.0.0/0

  db:
    image: postgres:latest
    networks:
      - hmpps
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

networks:
  hmpps:
